dist: trusty
language: java

jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk10
  - openjdk11
  - openjdk12
  - openjdk13
  - openjdk14

jobs:
  include:
    - stage: Sonar check and code coverage reporting
      jdk: oraclejdk8
      addons:
        sonarcloud:
          organization: "valfirst-github"
          token:
            secure: "pA4FqOfVKuotCJ4NXKs7JMvD1635Defrw91zLoNh/R0oI5gOQ3VMqvGlK62jaJ/8c7Z12h6urKK3ItEe5OSKBa8q7399+qs0Q1RZg6kMa5mWV8yvWSRKsWkqhIpTcaCZgIgSru88Laziph60vL/gXy9l/DIdTLvZ8pn8YpO3T3BSeMhVdyhOW+JBARGXlRXS7zYraPzOeGQ6BNF8i2ylA45a+s3x4Mrl9P0IVK9qqHtSZpZ/+1ftYXOkZFufDuCLmFLo1+hHrcNbv4xOMfcbLqVOrT8gXr4B9WaWhz/as7fQf6tsj/HmnE2+jZBPPS4gWS0O5tA4932fFIcyxlcpfYlLND42Uy3tdID2BPJjdU1tlcv9F0W+DfycRd/TUWe7rPytacEIL9XYIce5Bc4JAL8xceTrffwUmi0KBiUFB1jYRhTzdE0xQAqPjO1hX1GQeLXQBQ6zDZbOZwmpZzLKW9bpepbbHfjtlX6UGma6HD2MOJVEUhB9RKlVYeQ9+JrBwWhgVmI1iNjqiMMzqkuJp5SzJyv6n1tcKDUhwubrY6ZDZhmBuYRER8NSZYudm3pqYZpnb+1d3D8JciBBkXbEV/PDvZ8AuhrE3jM2TB0z/KqnkqzWgSrt914xDWkNcyX1isMcvU4am6bPA9s2jB4NWa8Sc+CR9wPp3IAl3G4OxKI="
      script:
        - mvn clean verify coveralls:report
        - if [[ -n "${TRAVIS_PULL_REQUEST_SLUG}" && "${TRAVIS_PULL_REQUEST_SLUG}" != "${TRAVIS_REPO_SLUG}" ]]; then
            echo "The pull request from ${TRAVIS_PULL_REQUEST_SLUG} is an EXTERNAL pull request. Skip sonar analysis and Codacy coverage reporting.";
          else
            mvn sonar:sonar com.gavinmogan:codacy-maven-plugin:coverage -DcoverageReportFile=target/site/jacoco/jacoco.xml -DprojectToken=${CODACY_PROJECT_TOKEN} -DapiToken=${CODACY_API_TOKEN} -Dcommit=${TRAVIS_COMMIT} -Dsonar.projectKey=com.github.valfirst:slf4j-test;
          fi

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    
